// Autogenerated by colorConvert.lua
// Do not include this file

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, rgb>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, bgr>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, rgba>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, bgra>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, r_8>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, fr>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, frg>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, frgb>(from, to);
}

template <>
void convert<ePixelFormat::RGB_888, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb, frgba>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, rgb>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, bgr>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, rgba>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, bgra>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, r_8>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, fr>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, frg>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, frgb>(from, to);
}

template <>
void convert<ePixelFormat::BGR_888, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<bgr, frgba>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, rgb>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, bgr>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, rgba>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, bgra>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, r_8>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, fr>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, frg>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, frgb>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_8888, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba, frgba>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, rgb>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, bgr>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, rgba>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, bgra>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, r_8>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, fr>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, frg>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, frgb>(from, to);
}

template <>
void convert<ePixelFormat::BGRA_8888, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<bgra, frgba>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, rgb>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, bgr>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, rgba>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, bgra>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, r_8>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, fr>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, frg>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, frgb>(from, to);
}

template <>
void convert<ePixelFormat::R_8, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<r_8, frgba>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, rgb>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, bgr>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, rgba>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, bgra>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, r_8>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, fr>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, frg>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, frgb>(from, to);
}

template <>
void convert<ePixelFormat::RG_88, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<rg_88, frgba>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, rgb>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, bgr>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, rgba>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, bgra>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, r_8>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, fr>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, frg>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, frgb>(from, to);
}

template <>
void convert<ePixelFormat::RGB_332, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_332, frgba>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, rgb>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, bgr>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, rgba>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, bgra>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, r_8>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, fr>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, frg>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, frgb>(from, to);
}

template <>
void convert<ePixelFormat::RGB_233, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_233, frgba>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, rgb>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, bgr>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, rgba>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, bgra>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, r_8>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, fr>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, frg>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, frgb>(from, to);
}

template <>
void convert<ePixelFormat::RGB_565, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<rgb_565, frgba>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, rgb>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, bgr>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, rgba>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, bgra>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, r_8>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, fr>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, frg>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, frgb>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_4444, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_4444, frgba>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, rgb>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, bgr>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, rgba>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, bgra>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, r_8>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, fr>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, frg>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, frgb>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_5551, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_5551, frgba>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, rgb>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, bgr>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, rgba>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, bgra>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, r_8>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, fr>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, frg>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, frgb>(from, to);
}

template <>
void convert<ePixelFormat::RGBA_10_10_10_2, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<rgba_10_10_10_2, frgba>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, rgb>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, bgr>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, rgba>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, bgra>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, r_8>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, fr>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, frg>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, frgb>(from, to);
}

template <>
void convert<ePixelFormat::FR, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<fr, frgba>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, rgb>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, bgr>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, rgba>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, bgra>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, r_8>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, fr>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, frg>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, frgb>(from, to);
}

template <>
void convert<ePixelFormat::FRG, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<frg, frgba>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, rgb>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, bgr>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, rgba>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, bgra>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, r_8>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, fr>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, frg>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, frgb>(from, to);
}

template <>
void convert<ePixelFormat::FRGB, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<frgb, frgba>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::RGB_888>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, rgb>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::BGR_888>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, bgr>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::RGBA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, rgba>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::BGRA_8888>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, bgra>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::R_8>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, r_8>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::RG_88>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, rg_88>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::RGB_332>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, rgb_332>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::RGB_233>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, rgb_233>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::RGB_565>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, rgb_565>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::RGBA_4444>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, rgba_4444>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::RGBA_5551>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, rgba_5551>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::RGBA_10_10_10_2>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, rgba_10_10_10_2>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::FR>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, fr>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::FRG>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, frg>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::FRGB>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, frgb>(from, to);
}

template <>
void convert<ePixelFormat::FRGBA, ePixelFormat::FRGBA>(const Image2d &from, Image2d &to)
{
	copyImageData<frgba, frgba>(from, to);
}

