#!/usr/bin/lua

filename = "colorConvert.h"

pf = {"RGB_888", "BGR_888", "RGBA_8888", "BGRA_8888", "R_8", "RG_88", 
		"RGB_332", "RGB_233", "RGB_565", "RGBA_4444", "RGBA_5551", "RGBA_10_10_10_2",
		"FR", "FRG", "FRGB", "FRGBA"}

cf = {"rgb", "bgr", "rgba", "bgra", "r_8", "rg_88",
		"rgb_332", "rgb_233", "rgb_565", "rgba_4444", "rgba_5551", "rgba_10_10_10_2",
		"fr", "frg", "frgb", "frgba"}

if #pf ~= #cf then
	print("Syntax error")
	return
end

io.output(filename)
io.write("// Autogenerated by colorConvert.lua\n")
io.write("// Do not include this file\n\n")

for i=1, #pf do
	for j=1, #pf do
		io.write(string.format("template <>\n"))
		io.write(string.format("void convert<ePixelFormat::%s, ePixelFormat::%s>(const Image2d &from, Image2d &to)\n", pf[i], pf[j]))
		io.write("{\n")
		io.write(string.format("\tcopyImageData<%s, %s>(from, to);\n", cf[i], cf[j]))
		io.write("}\n\n")
	end
end

io.close()
