#!/usr/bin/lua

filename = "colorConvert.h"

pf = {"RGB_888", "BGR_888", "RGBA_8888", "BGRA_8888", "R_8", 
		"RGB_332", "RGB_565", "RGBA_4444", "RGBA_5551", "RGBA_10_10_10_2",
		"FR", "FRGB", "FRGBA",
		"RGBA_16_16_16_16", "GRAYSCALE8", "GRAYSCALE16", "FGRAYSCALE"}

cf = {"rgb", "bgr", "rgba", "bgra", "r_8",
		"rgb_332", "rgb_565", "rgba_4444", "rgba_5551", "rgba_10_10_10_2",
		"fr", "frgb", "frgba",
		"rgba_16_16_16_16", "grayscale8", "grayscale16", "fgrayscale"}

if #pf ~= #cf then
	print("Syntax error")
	return
end

io.output(filename)
io.write("// Autogenerated by colorConvert.lua\n")
io.write("// Do not include this file\n\n")

for i=1, #pf do
	for j=1, #pf do
		io.write(string.format("template <>\n"))
		io.write(string.format("void convert<ePixelFormat::%s, ePixelFormat::%s>(const Image &from, Image &to)\n", pf[i], pf[j]))
		io.write("{\n")
		io.write(string.format("\tcopyImageData<%s, %s>(from, to);\n", cf[i], cf[j]))
		io.write("}\n\n")
	end
end

io.close()
